/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package junit.gradle;

public class App {

    public int getAdd (int a, int b){
        return a + b;
    }

    public int getSubtract (int a, int b){
        return a - b;
    }

    public int getMultiply (int a, int b){
        return a * b;
    }

    public int getSplit (int a, int b){
        return a / b;
    }
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
